### ISSUE TITLE
Unable to set the postBody for importRows() / importTable() with Fusiontables

### ISSUE THREAD

**Issue by erikverheij** [google/google-api-php-client#470] opened 2015-02-02 15:36 UTC
In /Service/Fusiontables.php ImportRows() and importTable() do not allow to set the actual payload. 

Manually adding the postBody as a optional param does also not work as the content type is hard coded to application/x-www-form-urlencoded in maybeMoveParametersToBody() (https://github.com/google/google-api-php-client/blob/master/src/Google/Http/Request.php#L469).

Fusiontables requires csv formatted contents with content-type=application/octet-stream.

**Comment by ianbarber** [comment] 2015-02-05 20:03
Not familiar with the Freebase API, so you may do better on SO or similar. That said, if posting data is the issue, are you using the media upload options? I am wondering if it needs to be used in that manner (see the media upload example in examples/) in order to transfer the data correctly.

**Comment by erikverheij** [comment] 2015-02-14 10:25
I'm not sure why you refer to the Freebase API. 

The Google_Service_Drive_Files_Resource/insert() method used in the example actually allows to set the postbody as the first param. For the following methods of Fusion tables it should also be possible to set the postbody; 

Google_Service_Fusiontables_Table_Resource/importRows() - Currenty not possible to set the postbody
Google_Service_Fusiontables_Table_Resource/importTable() - Currenty not possible to set the postbody
Google_Service_Fusiontables_Table_Resource/patch() - Seems to work fine
Google_Service_Fusiontables_Table_Resource/replaceRows() - Currenty not possible to set the postbody
Google_Service_Fusiontables_Table_Resource/update() - Seems to work fine

See this page for more information about the options for uploading in fusion tables; https://developers.google.com/fusiontables/docs/v2/reference/table/replaceRows

**Comment by ianbarber** [comment] 2015-02-15 20:32
Sorry, just a typo re Freebase. Though no experience with fusion tables either. However, it sounds like the issue is with the generated template files though, if some methods are setup correctly and others aren't. Probablly the best thing to do is take a look at the API explorer/other client libraries and see how those requests are handled - it may be that you're not supposed to use them quite the same way, or it could be that the generator needs updating.

**Comment by BenWise9000** [comment] 2016-04-08 04:01
@erikverheij  API Version 1.1.7 works for me doing the following (for ReplaceRows):

```
        $client = new Google_Client();
        $client->setApplicationName('My application name');
        $serviceAccountName = 'something@something';

        $privateKey = file_get_contents('/path/to/keyfile.p12');

        $credentials = new \Google_Auth_AssertionCredentials(
            $serviceAccountName,
            ['https://www.googleapis.com/auth/fusiontables'],
            $privateKey
        );

        $client->setAssertionCredentials($credentials);
        if ($client->getAuth()->isAccessTokenExpired()) {
            $client->getAuth()->refreshTokenWithAssertion();
        }

        $service = new \Google_Service_Fusiontables($client);
        $tableId = 'aTableIdString';
        $tsvData = file_get_contents('/path/to/tsv/file.tsv');
        $reqData = $service->table->get($tableId);
        $service->table->replaceRows($tableId, ['postBody' => $reqData, 'data' => $tsvData, 'mimeType' => 'application/octet-stream',
            'uploadType' => 'multipart', 'delimiter' => "\t"]);
```

**Comment by tmatsuo** [comment] 2017-01-13 22:31
Hi, it seems like @BenWise9000 has a wordaround. @erikverheij Does it make sense to close this issue, or should we still fix this?

**Comment by erikverheij** [comment] 2017-01-14 02:01
Hi, sorry I missed  the workaround of @BenWis e9000. Currently I don't have access to the project using this library so closing this issue seems like the best option.

**Closed** 2017-01-14 02:02 UTC
Labels: needs-repro
