### ISSUE TITLE
Custom leeway value for JWT verification gets overwritten with '1'

### ISSUE THREAD

**Issue by TheMorganHub** [google/google-api-php-client#1430] opened 2018-06-01 22:26 UTC
This happens on the Verify.php file located [here](https://github.com/google/google-api-php-client/blob/master/src/Google/AccessToken/Verify.php) at the `getJwtService()` method

```
  private function getJwtService()
  {
    $jwtClass = 'JWT';
    if (class_exists('\Firebase\JWT\JWT')) {
      $jwtClass = 'Firebase\JWT\JWT';
    }

    if (property_exists($jwtClass, 'leeway')) {
      // adds 1 second to JWT leeway
      // @see https://github.com/google/google-api-php-client/issues/827
      $jwtClass::$leeway = 1;
    }
  }
```

The comment says that this was done to fix issue #827 and it says that it 'adds', but instead it overwrites. This causes lots of `BeforeValidException`s to be thrown because most servers require more than 1 sec of leeway.

For example, if I set the leeway like so `\Firebase\JWT\JWT::$leeway = 60;` and then call `verifyIdToken($id_token)`, my custom leeway will be overwritten with 1.

A simple fix would work like this:
`$jwtClass::$leeway += 1;`

This would respect custom values set by the user and have a default value of `1` for those that don't change the leeway.

Cheers.

**Comment by LindaLawton** [comment] 2018-06-04 06:35
@mattwhisenhunt please tag bug or needs investigation.

**Comment by bshaffer** [comment] 2018-06-13 15:51
closing as a duplicate of #1172

**Closed by bshaffer** 2018-06-13 15:51 UTC
Labels: priority: p2, type: bug
