### ISSUE TITLE
Cannot remove "SENT" label from email [Gmail API]

### ISSUE THREAD

**Issue by Jazzo** [google/google-api-php-client#1254] opened 2017-06-29 16:33 UTC
I cannot remove the "SENT" label from any email. This is my code:
```
$mods = new Google_Service_Gmail_ModifyMessageRequest();
$mods->setAddLabelIds(['UNREAD']);
$mods->setRemoveLabelIds('SENT');
$message = $this->_gmailService->users_messages->modify($userId, $messageId, $mods);
```
I think it could be a general Gmail API error because it does not work even in the [test env of users_messages.modify](https://developers.google.com/gmail/api/v1/reference/users/messages/modify?authuser=1). I can remove all the others labels but not "SENT".

Test it with the follow "_Request body_"
```
{
  "removeLabelIds": ["SENT"],
  "addLabelIds": ["UNREAD"]
}
```
I got this **ERROR 400** reply from the server:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidArgument",
    "message": "Invalid label: SENT"
   }
  ],
  "code": 400,
  "message": "Invalid label: SENT"
 }
}
```

**Comment by mattwhisenhunt** [comment] 2017-12-22 19:29
I am not on the GMail team but I think that is by design. Some labels you can't change.

**Comment by mattwhisenhunt** [comment] 2018-01-29 03:07
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Closed by mattwhisenhunt** 2018-01-29 03:07 UTC
Labels: type: question
