### ISSUE TITLE
Group listMembers URI error

### ISSUE THREAD

**Issue by eyes-919** [google/google-api-php-client#906] opened 2016-03-23 00:36 UTC
I can't get group listMembers because URI of listMembers API is wrong.

https://www.googleapis.com/admin/directory/v1/groups/groupKey,share%40g.xxxxxx.com/members:
(404) Resource Not Found: groupKey' in ./vendor/src/Google/Http/REST.php:110

It should be 
https://www.googleapis.com/admin/directory/v1/groups/share%40g.xxxxxx.com/members

./src/Google/Utils/URITemplate.php
248           $value = implode($list_sep, $values);

if I change it like this

$value = $values[1];

URI is OK and I can get response.

**Comment by tcurtin** [comment] 2016-04-01 16:47
I'm getting a similar error, but not sure if its the same cause, and the fix you mention above isn't resolving my issue.

Error calling GET https://www.googleapis.com/admin/directory/v1/groups/groupname%40domain.com/members: (404) Resource Not Found: groupKey

In URITemplate.php, changing
```
          $value = implode($list_sep, $values);
          if ($value == '') {
            return false;
          }

```
to 

```
          $value = implode($list_sep, $values[1]);
          if ($value == '') {
            return false;
          }

```
doesn't resolve the problem for me - same error.

I haven't actually tried this call in a while, so I'm not sure the last time it worked properly, but I don't believe it was caused by a change on my end...

FWIW, the API test also returns the same error "Resource Not Found: groupKey":
https://developers.google.com/admin-sdk/directory/v1/reference/members/list#try-it

**Comment by andreityuhai** [comment] 2017-01-31 11:14
I also had the same issue.
You're probably passing groupKey within optional parameters array. listMembers method is expecting groupKey to be first parameter and optParams array - as second parameter.

Proper request should look like:

```php
putenv("GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json");

$client = new Google_Client();
$client->useApplicationDefaultCredentials();
//@param $account - service account email
$client->setSubject($account);
$client->addScope(Google_Service_Directory::ADMIN_DIRECTORY_GROUP);

$service = new Google_Service_Directory($client);

$groupKey = $directory_group_id;
$optParams = array(
  'maxResults' => 1000
);

$results = $service->members->listMembers($groupKey, $optParams);
```

**Comment by mattwhisenhunt** [comment] 2017-12-22 20:30
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.

**Closed by mattwhisenhunt** 2017-12-22 20:30 UTC
