### ISSUE TITLE
Method setAuthConfig fails when using JSON string as parameter

### ISSUE THREAD

**Issue by idoqo** [google/google-api-php-client#1151] opened 2017-02-13 21:01 UTC
Given the names, I was expecting setAuthConfig() to accept a json string conforming to the format specified in the downloaded credentials file as its parameter unlike setAuthConfigFile() but it keeps breaking. Noticed this issue has been opened [here](https://github.com/google/google-api-php-client/issues/1097) but received no feedback.

**Comment by michaelbausor** [comment] 2017-02-28 00:23
Duplicate of https://github.com/google/google-api-php-client/issues/1097

**Closed by michaelbausor** 2017-02-28 00:23 UTC
