### ISSUE TITLE
Cannot handle token prior to 2017-11-11T07:03:06+0000","line":127,"exception":"Firebase\\JWT\\BeforeValidException","file":"\/var\/www\/html\/projectName\/vendor\/firebase\/php-jwt\/src\/JWT.php"

### ISSUE THREAD

**Issue by chauhanbhargav** [google/google-api-php-client#1341] opened 2017-11-17 06:14 UTC
**Error comes on server.**

This issue does not come on a local server, but when I will run this code on the server I will get an error every first time.

Here is my code and error message : 

Message : **Cannot handle token prior,"exception":"Firebase\\JWT\\BeforeValidException"**
```php
 $client = new Google_Client(['client_id' => env('GOOGLE_CLIENT_ID')]);
 $googlePayload = $client->verifyIdToken($token);
```

Thank you!

**Comment by mattwhisenhunt** [comment] 2017-11-20 21:07
You probably have a slight skew between the clock on the server that mints the tokens and the clock on the server that's validating the token - if the iat or nbf is in the future, then the token isn't yet valid.

One solution would be to use a small leeway, like this:
```php
JWT::$leeway = 5; // Allows a 5 second tolerance on timing checks
```

**Comment by mattwhisenhunt** [comment] 2018-01-08 19:23
Duplicate of #1172

**Closed by mattwhisenhunt** 2018-01-08 19:23 UTC
Labels: priority: p1, type: bug
