### ISSUE TITLE
PHP Fatal error Class 'GuzzleHttp\ClientInterface' not found

### ISSUE THREAD

**Issue by jshrek** [google/google-api-php-client#1345] opened 2017-11-21 01:28 UTC
Get the following error when require_once Client.php
PHP Fatal error:  Class 'GuzzleHttp\ClientInterface' not found in /home/somethingfrtv/public_html/somefolder/google-api-php-client/Client.php on line 1042

Have also require_once ALL other files in the API but this class does not seem to be defined anywhere:
	require_once __DIR__.'/google-api-php-client/Client.php';
	require_once __DIR__.'/google-api-php-client/Collection.php';
	require_once __DIR__.'/google-api-php-client/Exception.php';
	require_once __DIR__.'/google-api-php-client/Model.php';
	require_once __DIR__.'/google-api-php-client/Service.php';
	require_once __DIR__.'/google-api-php-client/AccessToken/Verify.php';
	require_once __DIR__.'/google-api-php-client/AccessToken/Revoke.php';
	require_once __DIR__.'/google-api-php-client/AuthHandler/AuthHandlerFactory.php';
	require_once __DIR__.'/google-api-php-client/AuthHandler/Guzzle5AuthHandler.php';
	require_once __DIR__.'/google-api-php-client/AuthHandler/Guzzle6AuthHandler.php';
	require_once __DIR__.'/google-api-php-client/Http/Batch.php';
	require_once __DIR__.'/google-api-php-client/Http/MediaFileUpload.php';
	require_once __DIR__.'/google-api-php-client/Http/REST.php';
	require_once __DIR__.'/google-api-php-client/Service/Exception.php';
	require_once __DIR__.'/google-api-php-client/Service/Resource.php';
	require_once __DIR__.'/google-api-php-client/Task/Exception.php';
	require_once __DIR__.'/google-api-php-client/Task/Retryable.php';
	require_once __DIR__.'/google-api-php-client/Task/Runner.php';
	require_once __DIR__.'/google-api-php-client/Utils/UnTemplate.php';

**Comment by bhuwan81** [comment] 2017-11-21 13:20
oh

**Comment by slaFFik** [comment] 2017-11-21 16:14
https://github.com/google/google-api-php-client/issues/1344#issuecomment-346077047

**Comment by mattwhisenhunt** [comment] 2017-11-21 17:31
Duplicate of #1344.

**Closed by mattwhisenhunt** 2017-11-21 17:31 UTC
