### ISSUE TITLE
Could you please add the "trash method" of Files.php  like delete method?

### ISSUE THREAD

**Issue by MiguelQueiroz** [google/google-api-php-client#1481] opened 2018-07-12 15:56 UTC
Like   public function delete($fileId, $optParams = array())
  {
    $params = array('fileId' => $fileId);
    $params = array_merge($params, $optParams);
    return $this->call('delete', array($params));
  }

Why not have the trash method aswell?
I know i can hack the file and  do it on my own, but i think you could also add it to the source code

**Comment by mattwhisenhunt** [comment] 2018-07-12 19:39
Duplicate of #1366

**Comment by mattwhisenhunt** [comment] 2018-07-12 19:47
@MiguelQueiroz The DIY workaround is to run the [generator](https://pypi.org/project/google-apis-client-generator/) on the [v2 json](https://www.googleapis.com/discovery/v1/apis/drive/v2/rest) file. It may require a little Python knowledge though.

**Comment by mattwhisenhunt** [comment] 2018-08-15 17:48
@MiguelQueiroz, I ran into this page last week: https://developers.google.com/drive/api/v3/migration
It explains why trash went away.

Looks like you can call `update(['trashed'=>true])`

**Closed by mattwhisenhunt** 2018-08-15 17:48 UTC
Labels: priority: p2, status: blocked, type: bug
