### ISSUE TITLE
Can't set expiration time permissions

### ISSUE THREAD

**Issue by J05HI** [google/google-api-php-client#1228] opened 2017-05-20 11:59 UTC
Maby this is a bug:
https://stackoverflow.com/questions/42986256/google-drive-sdk-can-not-set-expiration-time-permissions

**Comment by kevinkhuat** [comment] 2017-05-22 04:42
I am able to replicate the same issue you described. I debugged through the code and I didn't see anything stand out. If I have time this week, I'll try to directly hit the api using Postman to see if I get different results.

**Comment by J05HI** [comment] 2017-05-22 05:20
@kevinkhuat 
Okay great :)

**Comment by kevinkhuat** [comment] 2017-05-25 15:53
@J05HI 
I was able to hit the api directly using Postman, and I was not able to add an expiration time. I didn't see an option to set an expirationTime when creating a new permission. I did see one for updating one
https://developers.google.com/drive/v3/reference/permissions/update

I tried making a request to update the permission, but I got this message:

`{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "cannotSetExpiration",
    "message": "Expiration dates cannot be set on this item."
   }
  ],
  "code": 403,
  "message": "Expiration dates cannot be set on this item."
 }
}
`

I'm not too sure why the permission can't be set.

**Comment by J05HI** [comment] 2017-05-25 16:19
@kevinkhuat 
Thanks for your effort! Maybe a bug.
A Google guy should look at this

**Comment by J05HI** [comment] 2017-10-13 10:46
@bshaffer
Noone would like to fix this?

**Comment by mattwhisenhunt** [comment] 2017-12-27 21:42
Duplicate of [#36760655](https://issuetracker.google.com/issues/36760655), [#36761485](https://issuetracker.google.com/issues/36761485)

**Closed by mattwhisenhunt** 2017-12-27 21:42 UTC

**Comment by J05HI** [comment] 2017-12-27 21:50
Thanks!
I hope it'll be fixed soon :)

**Comment by michelkommers** [comment] 2022-06-20 14:25
I suddenly started receiving this error, in an already working solution yesterday, can you guys check if you made any regression or something? the error appear when setting an expiration date on a pdf file. (this worked fine until yesterday)

Return message:

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "cannotSetExpiration",
    "message": "Expiration dates cannot be set on this item."
   }
  ],
  "code": 403,
  "message": "Expiration dates cannot be set on this item."
 }
}
