### ISSUE TITLE
Reference to undefined variable causing HTTP failure (v1)

### ISSUE THREAD

**Issue by DavidAnderson684** [google/google-api-php-client#1359] opened 2017-12-22 21:34 UTC
(Re-open of https://github.com/google/google-api-php-client/issues/871 , as requested).

In the v1 branch, in src/Google/IO/Stream.php, line 154 is:

`$respHttpCode = $this->getHttpResponseCode($http_response_header);`

There are no previous references to $http_response_header (and only one later one), and it's not obvious how to correct it. Attempting to use the stream handler gives a PHP warning for the undefined variable at this line, and also fails.

**Comment by mattwhisenhunt** [comment] 2017-12-27 21:17
Duplicate of #871

**Closed by mattwhisenhunt** 2017-12-27 21:17 UTC
