### ISSUE TITLE
Error: 2nd argument of array_merge() must be an array

### ISSUE THREAD

**Issue by naveedali2** [google/google-api-php-client#1484] opened 2018-07-23 11:36 UTC
$api_response = $youtube_analytics_service->reports->query($channel_id, $start_date, $end_date, $metrics, ['dimensions' => $dimensions]);

The above line got the response successfully when library version was 2.2.1 but as soon as the library was updated to 2.2.2 we got the error mentioned in title.

google\apiclient-services\src\Google\Service\YouTubeAnalytics\Resource\Reports.php(90): array_merge(Array, 'channel==UCoy6F...');

**Comment by mattwhisenhunt** [comment] 2018-07-27 16:21
Hi @naveedali2 !

I have looked at this and can't reproduce this behavior. Would you run a `composer show` and let me know what version google/apiclient-services is on?

**Comment by mattwhisenhunt** [comment] 2018-08-01 16:43
Duplicate of #1489

**Closed by mattwhisenhunt** 2018-08-01 16:43 UTC
Labels: needs more info, priority: p2, type: bug

**Comment by AroundtheGlobe** [comment] 2018-08-01 17:15
I've got the same error with similar code after updating the library. 
composer show output: 
google/apiclient              v2.2.2  Client library for Google APIs
google/apiclient-services     v0.64   Client library for Google APIs
google/auth                   v1.3.2  Google Auth Library for PHP

I am trying to execute this code: 
`$json = $analytics->reports->query('channel=='.$arrRow['youtubeid'].'', $datePast , $today, 'views', array('dimensions' => 'country', 'sort' => '-views'));` 

When I replace the old(er) Google library the code above works again.
