### ISSUE TITLE
Custom leeway value overwritten in Verify.php

### ISSUE THREAD

**Issue by vocoded** [google/google-api-php-client#1060] opened 2016-09-26 22:07 UTC
Per previous issue #829, code was added to provide a 1 second allowable expiration offset.  Unfortunately this code overwrites any previous value associated with this property.  I have a small patch to apply the offset only if the previous value is at its default.

**Comment by mattwhisenhunt** [comment] 2018-01-08 19:23
Duplicate of #1172

**Closed by mattwhisenhunt** 2018-01-08 19:23 UTC
Labels: type: bug
