### ISSUE TITLE
Same response with different access token(different user) with Google api php client

### ISSUE THREAD

**Issue by donriga** [google/google-api-php-client#821] opened 2016-01-31 14:16 UTC
I have created an web app which fetched users drive information and show it on a browser. It is working fine for single user but when I try this app with different account it still shows same result for both the user. I checked the logs and there are different access token different user. When I am fetching the result from http get call using those access token I get different result. I think some issue is there with the Google api php client.

**Comment by mTorres** [comment] 2016-02-01 11:49
Maybe related to #819?

**Comment by donriga** [comment] 2016-02-01 12:42
Yes, how to fix? Bug?

**Comment by mTorres** [comment] 2016-02-03 13:47
Ok more information, I've tried with different versions of the google/apiclient, the google/auth and guzzlehttp/guzzle. The summary is as follows:

|APICLIENT | AUTH | Guzzle | Result |
| --- | --- | --- | --- |
| 2.0-RC1 | 0.3 | 5.2 | OK |
| 2.0-RC2 | 0.4 | 5.2 | OK |
| 2.0-RC3 | 0.4 | 5.2 | OK |
| 2.0-RC4 | 0.5 | 5.2 | error|
| 2.0-RC4 | 0.5 | 6.0 | error |

In conclusion, from 2.0-RC1..RC3 it's working but RC4 shows the issue

**Comment by donriga** [comment] 2016-02-03 13:51
Waiting to fix))

**Comment by bshaffer** [comment] 2016-02-10 00:02
The problem is the underlying `google/auth` library's caching implementation is broken. The cache keys which get generated are not unique.

I've removed the caching entirely for now in #842

**Comment by bshaffer** [comment] 2016-02-10 23:49
This is now fixed in [RC5](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC5). Please update to this version and reopen this issue if the problem continues.

Thank you!

**Closed by bshaffer** 2016-02-10 23:49 UTC
Labels: bug

**Comment by 4rthem** [comment] 2019-12-11 13:54
The issue should be reopened.

I use this lib in a worker which maintains cache in memory.
Each time a message is consumed, I set the new access token (for a different user) but the previous one is preserved. This leads to a dangerous security concern.

I believe the cache should be disabled by default (even `MemoryCacheItemPool` for persistent scripts handling many tasks).

**Comment by ildarius** [comment] 2021-03-01 20:07
Same issue, waiting for the fix

**Comment by ildarius** [comment] 2021-03-01 20:10
> The issue should be reopened.
> 
> I use this lib in a worker which maintains cache in memory.
> Each time a message is consumed, I set the new access token (for a different user) but the previous one is preserved. This leads to a dangerous security concern.
> 
> I believe the cache should be disabled by default (even `MemoryCacheItemPool` for persistent scripts handling many tasks).

do you have a workaround?

**Comment by JustinBeckwith** [comment] 2021-03-01 23:09
@ildarius This is a 5 year old issue - if you are still having issues with the library, please feel free to open a new issue and reference this one.
