### ISSUE TITLE
Fatal error:  Uncaught exception 'Google_IO_Exception' with message 'SSL certificate problem: self signed certificate'

### ISSUE THREAD

**Issue by diz123** [google/google-api-php-client#756] opened 2015-11-20 03:37 UTC
What's that mean ?
I just start use google api php for month.My code worked fine for over 3 week.But last night i got that error. And after 30 minute it's run ok ??
Fatal error:  Uncaught exception 'Google_IO_Exception' with message 'SSL certificate problem: self signed certificate'

**Comment by sraul2015** [comment] 2015-12-16 10:41
Even I am facing same issue. I tried sample example on local environment for the first time and it gave same error. Has anyone resolved this? what is the cause? any pointers

**Comment by bshaffer** [comment] 2015-12-16 20:04
What is your OS / PHP version?

**Comment by mattwhisenhunt** [comment] 2017-12-22 20:06
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Closed by mattwhisenhunt** 2017-12-22 20:06 UTC
