### ISSUE TITLE
Use PSR-1 for namespacing

### ISSUE THREAD

**Issue by FrontEndCoffee** [google/google-api-php-client#1199] opened 2017-04-11 13:53 UTC
As stated in PSR-1 section: Namespaces and Classes. In PHP code written in PHP 5.3 or after must use formal namespaces.

<a href="http://www.php-fig.org/psr/psr-1/#namespace-and-class-names"><img width="761" alt="screen shot 2017-04-11 at 15 39 40" src="https://cloud.githubusercontent.com/assets/16303480/24912315/078cb176-1ece-11e7-8e9c-a07cbdb06312.png"><p>PHP-FIG: PSR-1, section: Namespaces and Classes</p></a>

PSR-1 also states that code written for PHP 5.2 and below must follow the pseudo naming convention, which is now used throughout the code base:

```php
class Google_Service_Resource
```

Since the codebase is written for PHP 5.4 and after, the project must follow the formal standard.

This problem is present in all branches of this repository.

**Comment by net-tools** [comment] 2017-04-12 07:21
Hi,

Although I understand your point, I don't see why (**from a user perspective**) we would have to **break existing code** "just" to introduces namespaces instead of pseudo naming convention such as `Google_Service_Resource`. That's a lot of work (in the API here, and in users scripts) for a small benefit.

And if you really want to stick to PSR-x, I think it's only recommandations ; by the way, from your excerpt : 

> "code written for 5.2.x and before SHOULD use..."

 "SHOULD" is not "MUST" ;-)

Let's see what @bshaffer and others users thinks of this "issue".

**Comment by bshaffer** [comment] 2017-04-12 17:23
I agree that namespaces are great and we eventually want to use them. 

This is not something we have any near plans of doing, as @net-tools mentions this is not really practical and creates no real problems for our users.

Adding to `v3` milestone, however, so we don't forget about it.

**Comment by FrontEndCoffee** [comment] 2017-04-16 16:16
I understand your choice, though I would like to remind you that if you want to eventually do it it might be better to do it early so less code gets broken.

**Comment by mattwhisenhunt** [comment] 2017-12-22 19:56
Duplicate of #692

**Closed** 2017-12-22 19:57 UTC
Labels: priority: p2, type: feature request
