### ISSUE TITLE
getEmails() misleading method documentation

### ISSUE THREAD

**Issue by bologer** [google/google-api-php-client#1437] opened 2018-06-08 07:13 UTC
You make request to and get info about user from Google plus: 
```php
...
$client->setRedirectUri($redirectUri);
$client->fetchAccessTokenWithAuthCode($_GET['code']));
$googlePlus = new Google_Service_Plus($client);
$user = $googlePlus->people->get('me');
```

Then trying to get email info: 

```php 
$user->getEmails()
```

By the method doc it is supposed to return `@return Google_Service_Plus_PersonEmails`, but as the result you get an array and get the value of the email you need to do the following: 

```php 
$user->getEmails()[0]->getValue()
```

Probably not the best thing for the `me`, as it is logical to return only one as result. 

I would say the following would be much more comfy: 
```php 
$user->getEmails()->getValue()
```

Or change the doc to: 
```php
@return Google_Service_Plus_PersonEmails[]
```

If this is how it is supposed to be, then I would say that the following:

```php 
$user->getImage()->getUrl()
```

should be changed to:

```php 
$user->getImage()[0]->getUrl()
```

**Comment by LindaLawton** [comment] 2018-06-11 14:09
What documentation are you referring  to?  do you have a link?

**Comment by bologer** [comment] 2018-06-11 14:16
@LindaLawton [source code documentation](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Plus/Person.php#L154)

**Comment by LindaLawton** [comment] 2018-06-11 15:22
That's just the generated source code for this library. 

 have you tried checking the documentation?

https://developers.google.com/people/api/rest/#rest-resource-v1people

**Comment by mattwhisenhunt** [comment] 2018-06-11 23:59
Duplicate of #443

**Closed by mattwhisenhunt** 2018-06-11 23:59 UTC
Labels: priority: p2, type: bug, type: docs

**Comment by mattwhisenhunt** [comment] 2018-06-12 05:06
Thanks for your earlier feedback, Alexander.
There is no plan to change the API as defined at https://developers.google.com/people/api/rest/. You can see  at the top of the discovery doc it gets little tweaks all the time but nothing on the scale that you are asking for.

There is a plan to generate better IDE helps (#443) that might override source code documentation in IDEs and text editors. But that is low priority internally and hasn't piqued anyone's interest in the community yet.

**Comment by bologer** [comment] 2018-06-12 06:05
@mattwhisenhunt okay, thank you for quick reply.
